//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.Parsing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParsingText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParsingText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.Parsing.ParsingText", typeof(ParsingText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error.
        /// </summary>
        public static string ParserState_Error {
            get {
                return ResourceManager.GetString("ParserState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspecting....
        /// </summary>
        public static string ParserState_Inspecting {
            get {
                return ResourceManager.GetString("ParserState_Inspecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading references....
        /// </summary>
        public static string ParserState_LoadingReference {
            get {
                return ResourceManager.GetString("ParserState_LoadingReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed.
        /// </summary>
        public static string ParserState_Parsed {
            get {
                return ResourceManager.GetString("ParserState_Parsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing....
        /// </summary>
        public static string ParserState_Parsing {
            get {
                return ResourceManager.GetString("ParserState_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string ParserState_Pending {
            get {
                return ResourceManager.GetString("ParserState_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ParserState_Ready {
            get {
                return ResourceManager.GetString("ParserState_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string ParserState_Resolved {
            get {
                return ResourceManager.GetString("ParserState_Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolver Error.
        /// </summary>
        public static string ParserState_ResolverError {
            get {
                return ResourceManager.GetString("ParserState_ResolverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving declarations....
        /// </summary>
        public static string ParserState_ResolvingDeclarations {
            get {
                return ResourceManager.GetString("ParserState_ResolvingDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving references....
        /// </summary>
        public static string ParserState_ResolvingReferences {
            get {
                return ResourceManager.GetString("ParserState_ResolvingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not {0} instances of &apos;{1}&apos; in &apos;{2}&apos;.
        /// </summary>
        public static string StringExtensionsArgumentException {
            get {
                return ResourceManager.GetString("StringExtensionsArgumentException", resourceCulture);
            }
        }
    }
}
